// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations;

[DbContext(typeof(DataContext))]
[Migration("20260702014357_OffsetChangedToDateTime")]
partial class _20260702014357_OffsetChangedToDateTime
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.5.26302.115");

        modelBuilder.Entity("Domain.ChatEvent", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<Guid>("ChatId")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("TimeStamp")
                    .HasColumnType("TEXT");

                b.Property<string>("Type")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("TEXT");

                b.Property<Guid>("UserId")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.HasIndex("ChatId", "TimeStamp");

                b.ToTable("ChatEvents");
            });

        modelBuilder.Entity("Domain.ChatMessage", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<Guid>("AuthorId")
                    .HasColumnType("TEXT");

                b.Property<string>("Body")
                    .IsRequired()
                    .HasMaxLength(2000)
                    .HasColumnType("TEXT");

                b.Property<Guid>("ChatId")
                    .HasColumnType("TEXT");

                b.Property<bool>("IsHidden")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("TimeStamp")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("AuthorId");

                b.HasIndex("ChatId", "TimeStamp");

                b.ToTable("ChatMessages");
            });

        modelBuilder.Entity("Domain.KitChat", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<Guid>("SessionId")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("SessionId")
                    .IsUnique();

                b.ToTable("Chats");
            });

        modelBuilder.Entity("Domain.KitEvent", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<Guid?>("CreatedBy")
                    .HasColumnType("TEXT");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(4000)
                    .HasColumnType("TEXT");

                b.Property<DateTime>("EndDate")
                    .HasColumnType("TEXT");

                b.Property<string>("Image")
                    .HasMaxLength(2048)
                    .HasColumnType("TEXT");

                b.Property<DateTime>("StartDate")
                    .HasColumnType("TEXT");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.Property<Guid?>("UpdatedBy")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("StartDate");

                b.ToTable("Events");
            });

        modelBuilder.Entity("Domain.KitSession", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("AccessLevel")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("TEXT");

                b.Property<string>("Category")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<Guid?>("CreatedBy")
                    .HasColumnType("TEXT");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(4000)
                    .HasColumnType("TEXT");

                b.Property<TimeSpan>("Duration")
                    .HasColumnType("TEXT");

                b.Property<Guid>("EventId")
                    .HasColumnType("TEXT");

                b.Property<string>("Image")
                    .HasMaxLength(2048)
                    .HasColumnType("TEXT");

                b.Property<Guid>("SpeakerId")
                    .HasColumnType("TEXT");

                b.Property<string>("Sponsor")
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<DateTime>("StartTime")
                    .HasColumnType("TEXT");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.Property<Guid?>("UpdatedBy")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("EventId");

                b.HasIndex("SpeakerId");

                b.HasIndex("StartTime");

                b.ToTable("Sessions");
            });

        modelBuilder.Entity("Domain.KitUser", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<int>("AccessFailedCount")
                    .HasColumnType("INTEGER");

                b.Property<string>("Bio")
                    .HasMaxLength(2000)
                    .HasColumnType("TEXT");

                b.Property<string>("City")
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<string>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("TEXT");

                b.Property<string>("Country")
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<string>("Email")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<bool>("EmailConfirmed")
                    .HasColumnType("INTEGER");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<string>("Industry")
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<string>("Interests")
                    .HasMaxLength(1000)
                    .HasColumnType("TEXT");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<bool>("LockoutEnabled")
                    .HasColumnType("INTEGER");

                b.Property<DateTimeOffset?>("LockoutEnd")
                    .HasColumnType("TEXT");

                b.Property<string>("NormalizedEmail")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("NormalizedUserName")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("Organization")
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<string>("PasswordHash")
                    .HasColumnType("TEXT");

                b.Property<string>("PhoneNumber")
                    .HasColumnType("TEXT");

                b.Property<bool>("PhoneNumberConfirmed")
                    .HasColumnType("INTEGER");

                b.Property<string>("ProfileImage")
                    .HasMaxLength(2048)
                    .HasColumnType("TEXT");

                b.Property<string>("Pronouns")
                    .HasMaxLength(50)
                    .HasColumnType("TEXT");

                b.Property<string>("SecurityStamp")
                    .HasColumnType("TEXT");

                b.Property<string>("State")
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<string>("Title")
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<bool>("TwoFactorEnabled")
                    .HasColumnType("INTEGER");

                b.Property<string>("UserName")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("NormalizedEmail")
                    .HasDatabaseName("EmailIndex");

                b.HasIndex("NormalizedUserName")
                    .IsUnique()
                    .HasDatabaseName("UserNameIndex");

                b.ToTable("AspNetUsers", (string)null);
            });

        modelBuilder.Entity("Domain.KitVideo", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<Guid?>("CreatedBy")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("EndedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("PlaybackUrl")
                    .IsRequired()
                    .HasMaxLength(2048)
                    .HasColumnType("TEXT");

                b.Property<Guid>("SessionId")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("StartedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("TEXT");

                b.Property<TimeSpan?>("TotalDuration")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.Property<Guid?>("UpdatedBy")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("SessionId")
                    .IsUnique();

                b.ToTable("Videos");
            });

        modelBuilder.Entity("Domain.ModerationEvent", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<Guid>("ChatId")
                    .HasColumnType("TEXT");

                b.Property<string>("Command")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("TEXT");

                b.Property<Guid>("TargetId")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("TimeStamp")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("TargetId");

                b.HasIndex("ChatId", "TimeStamp");

                b.ToTable("ModerationEvents");
            });

        modelBuilder.Entity("Domain.ShowControl", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<Guid>("ChatId")
                    .HasColumnType("TEXT");

                b.Property<string>("Command")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("TEXT");

                b.Property<DateTime>("TimeStamp")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("ChatId", "TimeStamp");

                b.ToTable("ShowControls");
            });

        modelBuilder.Entity("Domain.UserAttending", b =>
            {
                b.Property<Guid>("UserId")
                    .HasColumnType("TEXT");

                b.Property<Guid>("SessionId")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("CheckedInAt")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("RegisteredAt")
                    .HasColumnType("TEXT");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("TEXT");

                b.Property<TimeSpan?>("TimeViewed")
                    .HasColumnType("TEXT");

                b.HasKey("UserId", "SessionId");

                b.HasIndex("SessionId");

                b.ToTable("UserAttendings");
            });

        modelBuilder.Entity("Domain.UserFollowing", b =>
            {
                b.Property<Guid>("ObserverId")
                    .HasColumnType("TEXT");

                b.Property<Guid>("TargetId")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("FollowedAt")
                    .HasColumnType("TEXT");

                b.HasKey("ObserverId", "TargetId");

                b.HasIndex("TargetId");

                b.ToTable("UserFollowings");
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("NormalizedName")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("NormalizedName")
                    .IsUnique()
                    .HasDatabaseName("RoleNameIndex");

                b.ToTable("AspNetRoles", (string)null);
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("ClaimType")
                    .HasColumnType("TEXT");

                b.Property<string>("ClaimValue")
                    .HasColumnType("TEXT");

                b.Property<Guid>("RoleId")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("RoleId");

                b.ToTable("AspNetRoleClaims", (string)null);
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("ClaimType")
                    .HasColumnType("TEXT");

                b.Property<string>("ClaimValue")
                    .HasColumnType("TEXT");

                b.Property<Guid>("UserId")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("AspNetUserClaims", (string)null);
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
            {
                b.Property<string>("LoginProvider")
                    .HasColumnType("TEXT");

                b.Property<string>("ProviderKey")
                    .HasColumnType("TEXT");

                b.Property<string>("ProviderDisplayName")
                    .HasColumnType("TEXT");

                b.Property<Guid>("UserId")
                    .HasColumnType("TEXT");

                b.HasKey("LoginProvider", "ProviderKey");

                b.HasIndex("UserId");

                b.ToTable("AspNetUserLogins", (string)null);
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
            {
                b.Property<Guid>("UserId")
                    .HasColumnType("TEXT");

                b.Property<Guid>("RoleId")
                    .HasColumnType("TEXT");

                b.HasKey("UserId", "RoleId");

                b.HasIndex("RoleId");

                b.ToTable("AspNetUserRoles", (string)null);
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
            {
                b.Property<Guid>("UserId")
                    .HasColumnType("TEXT");

                b.Property<string>("LoginProvider")
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .HasColumnType("TEXT");

                b.Property<string>("Value")
                    .HasColumnType("TEXT");

                b.HasKey("UserId", "LoginProvider", "Name");

                b.ToTable("AspNetUserTokens", (string)null);
            });

        modelBuilder.Entity("Domain.ChatEvent", b =>
            {
                b.HasOne("Domain.KitChat", null)
                    .WithMany("ChatEvents")
                    .HasForeignKey("ChatId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Domain.KitUser", "User")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("User");
            });

        modelBuilder.Entity("Domain.ChatMessage", b =>
            {
                b.HasOne("Domain.KitUser", "Author")
                    .WithMany()
                    .HasForeignKey("AuthorId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Domain.KitChat", null)
                    .WithMany("Messages")
                    .HasForeignKey("ChatId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Author");
            });

        modelBuilder.Entity("Domain.KitChat", b =>
            {
                b.HasOne("Domain.KitSession", "Session")
                    .WithOne("Chat")
                    .HasForeignKey("Domain.KitChat", "SessionId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Session");
            });

        modelBuilder.Entity("Domain.KitSession", b =>
            {
                b.HasOne("Domain.KitEvent", null)
                    .WithMany("RunOfShow")
                    .HasForeignKey("EventId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Domain.KitUser", "Speaker")
                    .WithMany()
                    .HasForeignKey("SpeakerId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Speaker");
            });

        modelBuilder.Entity("Domain.KitVideo", b =>
            {
                b.HasOne("Domain.KitSession", "Session")
                    .WithOne("Video")
                    .HasForeignKey("Domain.KitVideo", "SessionId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Session");
            });

        modelBuilder.Entity("Domain.ModerationEvent", b =>
            {
                b.HasOne("Domain.KitChat", null)
                    .WithMany("ModerationEvents")
                    .HasForeignKey("ChatId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Domain.KitUser", null)
                    .WithMany()
                    .HasForeignKey("TargetId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

        modelBuilder.Entity("Domain.ShowControl", b =>
            {
                b.HasOne("Domain.KitChat", null)
                    .WithMany("ShowControls")
                    .HasForeignKey("ChatId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Domain.UserAttending", b =>
            {
                b.HasOne("Domain.KitSession", "Session")
                    .WithMany("Attendees")
                    .HasForeignKey("SessionId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Domain.KitUser", "User")
                    .WithMany("Attending")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Session");

                b.Navigation("User");
            });

        modelBuilder.Entity("Domain.UserFollowing", b =>
            {
                b.HasOne("Domain.KitUser", "Observer")
                    .WithMany("Following")
                    .HasForeignKey("ObserverId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Domain.KitUser", "Target")
                    .WithMany("Followers")
                    .HasForeignKey("TargetId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Observer");

                b.Navigation("Target");
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
            {
                b.HasOne("Domain.KitUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
            {
                b.HasOne("Domain.KitUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Domain.KitUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
            {
                b.HasOne("Domain.KitUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Domain.KitChat", b =>
            {
                b.Navigation("ChatEvents");

                b.Navigation("Messages");

                b.Navigation("ModerationEvents");

                b.Navigation("ShowControls");
            });

        modelBuilder.Entity("Domain.KitEvent", b =>
            {
                b.Navigation("RunOfShow");
            });

        modelBuilder.Entity("Domain.KitSession", b =>
            {
                b.Navigation("Attendees");

                b.Navigation("Chat");

                b.Navigation("Video");
            });

        modelBuilder.Entity("Domain.KitUser", b =>
            {
                b.Navigation("Attending");

                b.Navigation("Followers");

                b.Navigation("Following");
            });
#pragma warning restore 612, 618
    }
}
